[book]
authors = ["Posthuman Studios", "Luiz Borges Gomide"]
language = "pt_BR"
multilingual = false
src = "src"
title = "Eclipse Phase 2e"
description = "O jogo de interpretação de sobrevivência transumana"

[build]
build-dir = "../docs/pt_br"
create-missing = false

[output.html]
additional-css = ["ep2e.css"]
no-section-label = false
git-repository-url = "https://github.com/luizbgomide/EclipsePhase2e-ptbr/tree/main/pt_br/src"
site-url = "/pt_br/"

[output.html.print]
enable = false

[output.html.fold]
enable = true

[output.html.search]
enable = true
use-boolean-and = true